apiVersion: v1
kind: Pod
metadata:
   name: db
   labels:
       name: mango
       app: todoapp
spec:
        containers:
           - image: mongo
             name: mongo
             ports:
               - name: mongo
                 containerPort: 27017
             volumeMounts:
                  - name: mongo-storage
                    mountPath: /data/db
        volumes:
            - name: mongo-storage
              hostPath:
                    path: /data/db
