apiVersion: v1
kind: Pod
metadata:
     name: web
     labels: 
        name: web
        app: todoapp
spec:
    containers:
           - image: nginx
             name: myweb
             ports: 
                - containerPort: 3000

